package io.chronohealth.clickup.workflow;

import io.chronohealth.clickup.client.ClickUpClient;
import io.chronohealth.clickup.client.ClickUpClientFactory;
import io.chronohealth.clickup.client.dto.CustomField;
import io.chronohealth.clickup.client.dto.CustomFieldValue;
import io.chronohealth.clickup.client.dto.NewSubtask;
import io.chronohealth.clickup.client.dto.Task;
import io.chronohealth.clickup.config.ClickUpProperties;
import io.chronohealth.clickup.config.ClickUpProperties.TagSubtaskRule;
import io.chronohealth.clickup.webhook.ClickUpEvent;
import io.chronohealth.clickup.webhook.ClickUpWebhookPayload.HistoryItem;
import io.chronohealth.clickup.webhook.EventHandler;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;
import tools.jackson.databind.JsonNode;

/**
 * When a configured tag (e.g. "backend") is added to a task, creates a subtask under it, e.g.
 * "Backend | &lt;parent name&gt;" with fixed and copied custom fields, priority, status and tags.
 * <p>
 * Idempotent and loop-safe:
 * <ul>
 *   <li>only tags that were <em>added</em> in this event trigger a rule (the tag history item's {@code after});
 *       removing a tag does nothing;</li>
 *   <li>tasks whose name already starts with the rule's prefix are skipped, so the generated subtask (which
 *       carries the same tag) never spawns another one;</li>
 *   <li>if the parent already has a subtask carrying the rule's tag (or the target title), nothing is created,
 *       so re-adding the tag and retries don't duplicate it.</li>
 * </ul>
 * The subtask is created in a single API call (fields included), so a failure never leaves a half-built subtask.
 */
@Component
public class TagSubtaskWorkflow implements EventHandler {

    static final String EVENT = "taskTagUpdated";
    private static final String TAG_ADDED_FIELD = "tag";

    private static final Logger log = LoggerFactory.getLogger(TagSubtaskWorkflow.class);

    private final ClickUpClientFactory clientFactory;
    private final CustomFieldValueMapper valueMapper;
    private final ClickUpProperties.TagSubtasks config;

    public TagSubtaskWorkflow(ClickUpClientFactory clientFactory, CustomFieldValueMapper valueMapper,
                              ClickUpProperties properties) {
        this.clientFactory = clientFactory;
        this.valueMapper = valueMapper;
        this.config = properties.workflows().tagSubtasks();
    }

    @Override
    public Set<String> eventTypes() {
        return config.enabled() && !config.rulesOrEmpty().isEmpty() ? Set.of(EVENT) : Set.of();
    }

    @Override
    public void handle(ClickUpEvent event) {
        Set<String> added = addedTags(event.historyItems());
        List<TagSubtaskRule> rules = config.rulesOrEmpty().stream()
                .filter(r -> added.contains(normalize(r.tag())))
                .toList();
        if (rules.isEmpty()) {
            return;
        }

        ClickUpClient client = clientFactory.forWorkspace(event.workspaceId());
        Task parent = client.getTask(event.taskId(), true);
        for (TagSubtaskRule rule : rules) {
            apply(client, parent, rule);
        }
    }

    private void apply(ClickUpClient client, Task parent, TagSubtaskRule rule) {
        String name = parent.name() == null ? "" : parent.name();
        if (name.startsWith(rule.titlePrefix())) {
            log.info("Task {} was generated by the '{}' rule; not creating another subtask", parent.id(), rule.tag());
            return;
        }
        String title = rule.titlePrefix() + name;
        Optional<Task> existing = parent.subtasksOrEmpty().stream()
                .filter(t -> hasTag(t, rule.tag()) || title.equals(t.name()))
                .findFirst();
        if (existing.isPresent()) {
            log.info("Task {} already has the '{}' subtask {}; skipping", parent.id(), rule.tag(), existing.get().id());
            return;
        }

        NewSubtask subtask = new NewSubtask(
                title,
                null,
                null,
                blankToNull(rule.status()),
                rule.copyPriority() && parent.priority() != null ? parent.priority().level() : null,
                null,
                rule.tagsOrEmpty().isEmpty() ? null : rule.tagsOrEmpty(),
                customFields(parent, rule));
        Task created = client.createSubtask(parent, subtask);
        log.info("Created '{}' subtask {} under task {}", rule.tag(), created.id(), parent.id());
    }

    private List<CustomFieldValue> customFields(Task parent, TagSubtaskRule rule) {
        List<CustomFieldValue> values = new ArrayList<>();
        for (Map.Entry<String, String> fixed : rule.setFieldsOrEmpty().entrySet()) {
            listField(parent, fixed.getKey(), rule).ifPresent(field ->
                    values.add(new CustomFieldValue(field.id(), valueMapper.fromConfig(field, fixed.getValue()))));
        }
        for (String fieldName : rule.copyFieldsOrEmpty()) {
            listField(parent, fieldName, rule)
                    .filter(CustomField::hasValue)
                    .flatMap(field -> valueMapper.toWriteValue(field).map(v -> new CustomFieldValue(field.id(), v)))
                    .ifPresent(values::add);
        }
        return values.isEmpty() ? null : values;
    }

    /**
     * Fields are resolved by name on the parent, whose list is also the subtask's list.
     */
    private static Optional<CustomField> listField(Task parent, String fieldName, TagSubtaskRule rule) {
        Optional<CustomField> field = parent.customFieldNamed(fieldName);
        if (field.isEmpty()) {
            log.warn("Field '{}' of the '{}' rule doesn't exist on the list of task {}; skipping it",
                    fieldName, rule.tag(), parent.id());
        }
        return field;
    }

    private static boolean hasTag(Task task, String tag) {
        return task.tags() != null && task.tags().stream()
                .anyMatch(t -> t.name() != null && normalize(t.name()).equals(normalize(tag)));
    }

    /**
     * Names of tags added in this event. ClickUp reports additions as history items with field "tag" and the
     * added tags in {@code after} (an array of tag objects, or a single one).
     */
    static Set<String> addedTags(List<HistoryItem> historyItems) {
        Set<String> tags = new HashSet<>();
        for (HistoryItem item : historyItems) {
            if (!TAG_ADDED_FIELD.equals(item.field()) || item.after() == null) {
                continue;
            }
            if (item.after().isArray()) {
                for (JsonNode tag : item.after()) {
                    addTagName(tags, tag);
                }
            } else {
                addTagName(tags, item.after());
            }
        }
        return tags;
    }

    private static void addTagName(Set<String> tags, JsonNode tag) {
        String name = tag.isString() ? tag.asString() : tag.path("name").asString(null);
        if (name != null && !name.isBlank()) {
            tags.add(normalize(name));
        }
    }

    private static String normalize(String tag) {
        return tag.trim().toLowerCase(Locale.ROOT);
    }

    private static String blankToNull(String value) {
        return value == null || value.isBlank() ? null : value;
    }
}
