-- Inbox of received ClickUp webhook events. Every verified delivery is stored here first, then processed;
-- failures are retried with backoff by the retry job until they succeed or are marked DEAD.
-- payload holds the normalized event (ids, event type, history item metadata) - no task content.
create table webhook_event (
    id              bigint generated by default as identity primary key,
    idempotency_key varchar(255)             not null,
    webhook_id      varchar(64)              not null,
    workspace_id    varchar(64)              not null,
    event_type      varchar(64)              not null,
    task_id         varchar(64),
    payload         text                     not null,
    status          varchar(16)              not null,
    attempts        integer                  not null default 0,
    next_attempt_at timestamp with time zone not null,
    locked_until    timestamp with time zone,
    last_error      varchar(1000),
    received_at     timestamp with time zone not null,
    updated_at      timestamp with time zone not null,
    constraint uk_webhook_event_idempotency_key unique (idempotency_key)
);

create index ix_webhook_event_due on webhook_event (status, next_attempt_at);
