-- Hourly audit: remembers how far the last successful run got, and the rule violations it found.
create table audit_state (
    id                 integer                  primary key,
    last_checked_until timestamp with time zone not null
);

-- One row per (rule, task). Open while resolved_at is null; reported once (notified_at), resolved when a later run
-- re-checks the task and the rule passes. No task content is stored: details only hold statuses/rule wording.
create table audit_violation (
    id            bigint generated by default as identity primary key,
    rule_id       varchar(100)             not null,
    task_id       varchar(64)              not null,
    details       varchar(1000)            not null,
    first_seen_at timestamp with time zone not null,
    last_seen_at  timestamp with time zone not null,
    resolved_at   timestamp with time zone,
    notified_at   timestamp with time zone,
    constraint uk_audit_violation_rule_task unique (rule_id, task_id)
);
